name: Build and Publish Wheels
on:
  workflow_dispatch:
  push:
    tags: "v*.*.*"  # Run on version tag pushes (adjust as needed)

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      # Provide PyPI token securely via GitHub Secrets
      MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python (optional: ensure a specific Python version on each platform)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # or matrix if building for multiple versions

      # Install dependencies on macOS
      - name: Install OpenSSL (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update &> /dev/null
          brew install openssl@1.1
        env:
          # Ensure pkg-config can find Homebrew OpenSSL
          PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig

      # Install dependencies on Windows
      - name: Install Perl and NASM (Windows)
        if: runner.os == 'Windows'
        run: choco install -y strawberryperl nasm

      # Build and publish using Maturin (handles Linux in Manylinux container)
      - name: Build and Publish with Maturin
        uses: PyO3/maturin-action@v1
        with:
          command: publish          # build and upload to PyPI
          args: --release           # build release wheels
          manylinux: "2014"         # Manylinux policy for Linux wheels (2014 is recommended)
          container: auto           # Use the default Manylinux container for Linux (auto-select)
          before-script-linux: |
            # Install OpenSSL and Perl in the manylinux container
            yum install -y perl-core openssl-devel

